# .github/workflows/main.yml
name: Test and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: bookingdb_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest
        env:
          TEST_DATABASE_URL: postgresql://admin:secret@localhost:5433/bookingdb_test
          # Add any other env vars your tests might need
          SECRET_KEY: test-secret-key

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test # This job only runs if the 'test' job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}