version: '3.8'

services:
  db:
    image: postgres:15-alpine  # Use a specific, lightweight Postgres version
    container_name: booking_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bookingdb
    ports:
      - "5432:5432"  # Map your local port 5432 to the container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    name: booking_db_data