version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: booking_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bookingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test_db:
    image: postgres:15-alpine
    container_name: booking_test_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bookingdb_test
    ports:
      - "5433:5432" # Note the different local port: 5433
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    name: booking_db_data
  postgres_test_data:
    name: booking_test_db_data