from pydantic import BaseModel
from typing import Optional

class ResourceBase(BaseModel):
    name: str
    description: Optional[str] = None
    url: str

class ResourceCreate(ResourceBase):
    pass

class Resource(ResourceBase):
    id: int

    class Config:
        from_attributes = True

"""
ResourceBase holds common fields.
ResourceCreate is what the user sends to the POST endpoint.
Resource is what we send back to the user, including the id generated by the database.

"""